Fixes to support API change in mojo 24.1.0

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,7 +13,7 @@ jobs:
         run: |
           curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh -
           modular auth ${{ secrets.MODULAR_AUTH }}
-          modular install --install-version 0.7.0 mojo
+          modular install --install-version 24.1.0 mojo
 
           pip install .
       - name: Integration Tests
@@ -29,17 +29,24 @@ jobs:
 
           # Tests that should fail
           if pytest example/tests/mod_a ; then
-            echo "This tests should fail"
+            echo "expected pytest exit code 0"
             exit 1
           fi
 
           # Test should fail because I am passing options for checking warnings
           rm -rf ~/.modular/.mojo_cache
           if pytest -W error example/tests/test_warning.mojo ; then
-            echo "This tests should fail"
+            echo "expected pytest exit code 0"
             exit 1
           fi
 
           # Test should not fail because I am not checking for warning
           rm -rf ~/.modular/.mojo_cache
           pytest example/tests/test_warning.mojo
+
+          # Test should fail because debug_assert is enabled
+          rm -rf ~/.modular/.mojo_cache
+          if pytest --mojo-assertions example/tests/test_debug_assert.mojo; then
+            echo "expected pytest exit code 0"
+            exit 1
+          fi
