Added Integration tests for warnings

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,12 +15,28 @@ jobs:
           modular auth ${{ secrets.MODULAR_AUTH }}
           modular install mojo
           pip install .
-      - name: Test
+      - name: Integration Tests
         run: |
           export MODULAR_HOME="/home/runner/.modular"
           export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"
+
+          # Tests that do not fail
           pytest example/tests/mod_b
+
+          # Tests that should fail
           if pytest example/tests/mod_a ; then
             echo "This tests should fail"
             exit 1
           fi
+
+          # Test should fail becuase I am passing options for checking warnings
+          rm -rf ~/.modular/.mojo_cache
+          if pytest -W error example/tests/test_warning.mojo ; then
+            echo "This tests should fail"
+            exit 1
+          fi
+
+          # Test should not fail becuase I am not checking for warning
+          rm -rf ~/.modular/.mojo_cache
+          pytest example/tests/test_warning.mojo
+
